use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs, io};

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let bundled_skills_dir = manifest_dir.join("bundled_skills");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let output_path = out_dir.join("bundled_skills_manifest.rs");

    let mut relative_paths = Vec::new();
    collect_files(
        &bundled_skills_dir,
        &bundled_skills_dir,
        &mut relative_paths,
    )?;
    relative_paths.sort();

    let mut generated = String::from(
        "// @generated by crates/zdx-assets/build.rs\nconst BUNDLED_SKILL_ASSETS: &[BundledSkillAsset] = &[\n",
    );

    for relative_path in relative_paths {
        generated.push_str("    BundledSkillAsset {\n");
        let _ = writeln!(generated, "        relative_path: {relative_path:?},");
        let _ = writeln!(
            generated,
            "        bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/bundled_skills/{relative_path}\")),"
        );
        generated.push_str("    },\n");
    }

    generated.push_str("];\n");
    fs::write(output_path, generated)
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_files(root, &path, out)?;
            continue;
        }

        if file_type.is_file() {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative_path = path
                .strip_prefix(root)
                .expect("bundled skill file should stay under bundled_skills")
                .to_string_lossy()
                .replace('\\', "/");
            out.push(relative_path);
        }
    }

    Ok(())
}
