use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs, io};

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    generate_manifest(
        &manifest_dir,
        &out_dir,
        "bundled_skills",
        "BUNDLED_SKILL_ASSETS",
        "BundledSkillAsset",
        "bundled_skills_manifest.rs",
    )?;

    generate_manifest(
        &manifest_dir,
        &out_dir,
        "bundled_commands",
        "BUNDLED_COMMAND_ASSETS",
        "BundledCommandAsset",
        "bundled_commands_manifest.rs",
    )?;

    Ok(())
}

fn generate_manifest(
    manifest_dir: &Path,
    out_dir: &Path,
    asset_dir_name: &str,
    array_name: &str,
    type_name: &str,
    output_file_name: &str,
) -> io::Result<()> {
    let asset_dir = manifest_dir.join(asset_dir_name);
    let output_path = out_dir.join(output_file_name);

    let mut relative_paths = Vec::new();
    if asset_dir.exists() {
        collect_files(&asset_dir, &asset_dir, &mut relative_paths)?;
    }
    relative_paths.sort();

    let mut generated = format!(
        "// @generated by crates/zdx-assets/build.rs\nconst {array_name}: &[{type_name}] = &[\n",
    );

    for relative_path in relative_paths {
        let _ = writeln!(generated, "    {type_name} {{");
        let _ = writeln!(generated, "        relative_path: {relative_path:?},");
        let _ = writeln!(
            generated,
            "        bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{asset_dir_name}/{relative_path}\")),"
        );
        generated.push_str("    },\n");
    }

    generated.push_str("];\n");
    fs::write(output_path, generated)
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_files(root, &path, out)?;
            continue;
        }

        if file_type.is_file() {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative_path = path
                .strip_prefix(root)
                .expect("bundled asset file should stay under its asset root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push(relative_path);
        }
    }

    Ok(())
}
