// @generated by generate_models
// DO NOT EDIT - regenerate with: cargo run --bin generate_models
//
// Source: https://models.dev/api.json
// Filter: provider=anthropic, tool_call=true, one per family

/// Definition of an available model.
#[derive(Debug, Clone)]
#[allow(dead_code)] // family is reserved for future use
pub struct ModelOption {
    /// Model ID (sent to API)
    pub id: &'static str,
    /// Display name for the picker
    pub display_name: &'static str,
    /// Model family (e.g., "claude-sonnet")
    pub family: &'static str,
}

/// Available models for the picker (one per family).
pub const AVAILABLE_MODELS: &[ModelOption] = &[
    ModelOption {
        id: "claude-haiku-4-5",
        display_name: "Claude Haiku 4.5 (latest)",
        family: "claude-haiku",
    },
    ModelOption {
        id: "claude-opus-4-5",
        display_name: "Claude Opus 4.5 (latest)",
        family: "claude-opus",
    },
    ModelOption {
        id: "claude-sonnet-4-5",
        display_name: "Claude Sonnet 4.5 (latest)",
        family: "claude-sonnet",
    },
];
